import type { Metadata } from 'next'
import Link from 'next/link'
import './styles/globals.css'

export const metadata: Metadata = {
  title: {
    template: '%s | Helix',
    default: 'Helix',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Link href='/'>Home</Link>
        &nbsp;
        <Link href='/blog'>Blog</Link>
        &nbsp;
        <Link href='/test'>Test page</Link>
        {children}
      </body>
    </html>
  )
}
